export const ADD_TODO = "ADD_TODO";
export const TOGGLE_ALLTODOS_STATE = "TOGGLE_ALLTODOS_STATE";
export const TOGGLE_TODO_STATE = "TOGGLE_TODO_STATE";
export const CHANGE_TODO_CONTENT = "CHANGE_TODO_CONTENT";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_COMPLETED_TODOS = "DELETE_COMPLETED_TODOS";